name: 'Obfuscated Commit Discord Webhook'
description: 'This GitHub Action sends simple discord messages for your commits, and supports obfuscating ones you want to keep secret'
branding:
  icon: git-commit
  color: blue

inputs:
  id:
    description: The Discord Webhook ID
    required: true
  token:
    description: The Discord Webhook Token
    required: true
  threadId:
    description: If you want to send the embed message in a specific thread
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'